version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=raouf
      - MONGO_INITDB_ROOT_PASSWORD=mongodb13579
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
